name: CI

on:
  push:
    branches:
      - main
    
permissions: 
  contents: read

jobs:
  code-coverage:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: codecov/codecov-action@v3
    - uses: step-security/harden-runner@int
