name: CI

on:
  push:
    branches:
      - main
    
permissions: 
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: step-security/harden-runner@int
      with:
        egress-policy: audit
