name: CI

on:
  pull_request:
    branches:
      - main
    
permissions: 
  contents: read

jobs:
  code-coverage:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089
    - uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
