name: CI
#test
on:
  push:
    branches:
      - main
    
permissions: 
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Harden Runner
      uses: step-security/harden-runner@int
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
    - run: curl https://www.stepsecurity.io/
