name: Spellcheck Action
on: 
  pull_request:
    paths:
      - '*.md'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089
    - uses: rojopolis/spellcheck-github-actions@aa00f5d4e79532b1e33a8ad259c826de1eac28a0
      name: Spellcheck
      with:
        source_files: '*.md'
        task_name: Markdown
